//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED7Studios.EzCar.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RED7Studios.EzCar.Languages.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Make sure the program is ran as administrator..
        /// </summary>
        public static string frmDateAndTime_AdminNote {
            get {
                return ResourceManager.GetString("frmDateAndTime_AdminNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time Settings.
        /// </summary>
        public static string frmDateAndTime_Name {
            get {
                return ResourceManager.GetString("frmDateAndTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string frmDateAndTime_Save {
            get {
                return ResourceManager.GetString("frmDateAndTime_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string frmMenu_Music {
            get {
                return ResourceManager.GetString("frmMenu_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string frmMenu_Name {
            get {
                return ResourceManager.GetString("frmMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string frmMenu_Settings {
            get {
                return ResourceManager.GetString("frmMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string frmMusic_Close {
            get {
                return ResourceManager.GetString("frmMusic_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string frmMusic_Menu {
            get {
                return ResourceManager.GetString("frmMusic_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string frmMusic_Name {
            get {
                return ResourceManager.GetString("frmMusic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string frmMusic_Open {
            get {
                return ResourceManager.GetString("frmMusic_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY A SONG.
        /// </summary>
        public static string frmMusic_PlayASong {
            get {
                return ResourceManager.GetString("frmMusic_PlayASong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins List.
        /// </summary>
        public static string frmPlugins_Name {
            get {
                return ResourceManager.GetString("frmPlugins_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp;&amp; Time.
        /// </summary>
        public static string frmSettings_DateAndTime {
            get {
                return ResourceManager.GetString("frmSettings_DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string frmSettings_GoBack {
            get {
                return ResourceManager.GetString("frmSettings_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string frmSettings_Name {
            get {
                return ResourceManager.GetString("frmSettings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string frmSettings_Plugins {
            get {
                return ResourceManager.GetString("frmSettings_Plugins", resourceCulture);
            }
        }
    }
}
